### ISSUE TITLE
Tables without headers

### ISSUE THREAD

**Issue by torokp** [adam-p/markdown-here#266]
Would you consider to include feature to allow tables without headers:
http://stackoverflow.com/a/17543474/319372

Sample:

a | b | c
d | e | f

Instread of:

 | | 
--- | --- | ---
a | b | c
d | e | f

**Comment by adam-p** [comment]
As a workaround, that the suggestion in that SO answer almost works. If you put this in MDH's Primary Styling CSS:

```css
th:empty {
  font-size: 0px;
  margin: 0;
  padding: 0;
  border: 0;
}
```

...You end up with this:

![image](https://cloud.githubusercontent.com/assets/425687/6806189/91096e62-d21d-11e4-9485-7de111632884.png)

Notice the one-pixel-thicker grey line at the top? That's from the `<tr>` border. I can't figure out a way to get rid of it cleanly, since there's no CSS parent selector (like, "select the `tr` elements that are parents of empty `th` elements"). 

This will affect all `tr` elems in `thead`, regardless of whether they're empty or not:
```css
thead > tr {
  padding: 0;
  margin: 0;
  border: 0;
}
```

But... the good news is that it doesn't seem to adversely affect the non-empty case! (...What the hell? I guess the `tr` border rule is redundant.)

Anyway, you still end up typing an empty header row, so I'm guessing this workaround doesn't satisfy you.
