### ISSUE TITLE
Add additional content wrapper

### ISSUE THREAD

**Issue by drKnoxy** [adam-p/markdown-here#312]
With two content wrappers we would be able to style emails to have a centered block section like you see in most marketing emails:

```css
.wrapper {
    background: #eee;
}
.content {
    background: #fff;
    padding: 10px;
    margin: 0 auto;
    max-width: 600px;
    min-width: 300px;
}
```

![screen shot 2015-11-18 at 10 25 47 am](https://cloud.githubusercontent.com/assets/604015/11245082/edeead22-8dde-11e5-95f4-5e35999fa26d.png)
