### ISSUE TITLE
Request: YAML Support in Code Blocks

### ISSUE THREAD

**Issue by shellscape** [adam-p/markdown-here#328]
Github now supports YAML syntax highlighting, and it would be a great addition to the extension. 

http://www.yaml.org/

Example:

```yml
thing: "foo"
bar:
 - baz
 - beep
 - boop
 - bop
```

After rendering with Markdown Here, the code appears unstyled.
