### ISSUE TITLE
Syntax highlighting CSS themes have wrong classes for languages

### ISSUE THREAD

**Issue by townba** [adam-p/markdown-here#336]
The syntax highlighting CSS themes appear to have the wrong classes for languages. (Perhaps there was a change to highlight.js?) For example, the "Default (Github)" theme has the following:
```css
.hljs-comment,
.hljs-template_comment,
.diff .hljs-header,
.hljs-javadoc {
  color: #998;
  font-style: italic;
}
```
and
```css
.diff .hljs-change {
  background: #0086b3;
}
```
However, the HTML elements created actually use `language-diff` rather than just `diff`.

The workaround is simple: Edit the "Syntax Highlighting CSS" in Options and change all the language-related classes. Here are my changes to the above rules:
```css
.hljs-comment,
.hljs-template_comment,
.language-diff .hljs-header,
.hljs-javadoc {
  color: #998;
  font-style: italic;
}
```
and
```css
.language-diff .hljs-change {
  background: #0086b3;
}
```

A simple test case can show if you've fixed it for the given language. Here's a small one for diff:

    ```diff
    Index: languages/ini.js
    ===================================================================
    --- languages/ini.js    (revision 199)
    +++ languages/ini.js    (revision 200)
    ! compress the size of the
    ! changes.
    ```
Without the changes above, it's all plain. With the changes, the first four lines are gray italics, and the last two have a background of cyan.
