### ISSUE TITLE
quotes in Blockquote

### ISSUE THREAD

**Issue by Didymograptus** [adam-p/markdown-here#456]
email client - Thunderbird 52.3.0, Windows 7
I want to automatically assign text within a Blockquote to have enclosing quotation marks. The following CSS works in the w3schools.com sandpit, but in Thunderbird the enclosing quotes are not included.

```css
blockquote {
background:#f9f9f9;
border-left:10px solid #996600;
margin:1.5em 10px;
padding:.5em 10px;
font-style: italic;
color: #666699;
quotes:"\201C""\201D""\2018""\2019";
}
blockquote:before {
content:open-quote;
}
blockquote:after {
content:close-quote;
}

```
Any ideas why not?
