### ISSUE TITLE
support for the <kbd> tag in yahoo mail ?

### ISSUE THREAD

**Issue by stephen147** [adam-p/markdown-here#565]
<kbd>Ctrl</kbd>

renders correctly in this, whereas it doesn't in Yahoo mail.

### Image in yahoo mail below of the same text

![ The same text as above. ]( https://imgur.com/DS2dIFp.png " Image: The same text as above. ")

---
Is this a limitation of MDhere or Yahoo mail.

**Comment by joanpau** [comment]
The defauls css shipped with markdown here does not include a particular style for `<kbd>` elements.
You can modify it adding these lines to support it:
```css
kbd {
 display: inline-block;
 margin: 0 .1em;
 padding: .1em .6em;
 font-family: sans-serif;
 font-size: 11px;
 line-height: 1.4;
 color: #242729;
 text-shadow: 0 1px 0 #ffffff;
 background-color: #e4e6e8;
 border: 1px solid #9fa6ad;
 border-radius: 3px;
 box-shadow: 0 1px 1px rgba(12,13,14,0.15),inset 0 1px 0 0 #ffffff;
 white-space: nowrap;
}
```

Would it be nice to have it in the default css? I think so!
It would also be nice to have a separated css for customizations or additions,
so that if the default css is updated with the extension, the changes would not be lost.
