### ISSUE TITLE
Question - Change the css style of the horizontal ruler

### ISSUE THREAD

**Issue by stephen147** [adam-p/markdown-here#619]
**If I do this**

```
---
```

**Which creates**

---

**How can I change the css style for this. I've tried**
```
hr {
  color: #49afd1;
}
```

**Comment by stephen147** [comment]
# this works

```css
  hr {
    background-color: #F8F8F8;
    display: block; height: 1px;
    border: 0; border-top: 2px solid #ccc;
    margin: 1em 0; padding: 0;
  }
```
